import pathlib

import nbformat
import nbformat.v4 as nbf
import pytest

from repo2nb.converter import convert
from repo2nb.notebook import make_writefile_cell
from repo2nb.reverse import reverse


def _make_deep_repo(tmp_path):
    repo = tmp_path / "proj"
    deep = repo / "a" / "b" / "c" / "d" / "e" / "f" / "g"
    deep.mkdir(parents=True)
    (repo / "top.py").write_text("top = 1\n")
    (deep / "leaf.py").write_text("leaf = 'deep'\n")
    return repo


def test_round_trip_deep_nesting(tmp_path):
    """The regression test for the nested-markdown risk: 7-level-deep tree reconstructs byte-for-byte."""
    repo = _make_deep_repo(tmp_path)
    nb_path = tmp_path / "out.ipynb"

    convert(repo, nb_path)
    out_dir = tmp_path / "restored"
    reverse(nb_path, out_dir, force=False)

    for rel in ["top.py", "a/b/c/d/e/f/g/leaf.py"]:
        assert (out_dir / rel).read_text() == (repo / rel).read_text()


def test_reverse_rejects_path_traversal(tmp_path, capsys):
    nb = nbf.new_notebook()
    evil = make_writefile_cell("safe.py", "ok")
    evil.metadata["repo2nb"]["path"] = "../../etc/passwd"
    nb.cells = [evil]
    nb_path = tmp_path / "evil.ipynb"
    nbformat.write(nb, str(nb_path))

    out_dir = tmp_path / "out"
    reverse(nb_path, out_dir)

    assert not (tmp_path / "etc" / "passwd").exists()
    assert not (out_dir / "etc").exists()
    assert "refusing unsafe path" in capsys.readouterr().out


def test_reverse_absolute_and_backslash_paths_rejected(tmp_path):
    nb = nbf.new_notebook()
    c1 = make_writefile_cell("x.py", "1")
    c1.metadata["repo2nb"]["path"] = "/abs/path.py"
    c2 = make_writefile_cell("y.py", "2")
    c2.metadata["repo2nb"]["path"] = "..\\windows\\evil.py"
    nb.cells = [c1, c2]
    nb_path = tmp_path / "n.ipynb"
    nbformat.write(nb, str(nb_path))

    out_dir = tmp_path / "out"
    reverse(nb_path, out_dir)
    assert list(out_dir.rglob("*")) == []


def test_reverse_no_metadata_fails_clearly(tmp_path, capsys):
    nb = nbf.new_notebook()
    nb.cells = [nbf.new_code_cell("print('hi')")]
    nb_path = tmp_path / "plain.ipynb"
    nbformat.write(nb, str(nb_path))

    with pytest.raises(SystemExit) as e:
        reverse(nb_path, tmp_path / "out")
    assert "not generated by repo2nb" in str(e.value)


def test_reverse_partial_cells_deleted(tmp_path):
    repo = _make_deep_repo(tmp_path)
    nb_path = tmp_path / "out.ipynb"
    convert(repo, nb_path)

    # user deleted the leaf writefile cell on Kaggle before downloading
    nb = nbformat.read(str(nb_path), as_version=4)
    nb.cells = [c for c in nb.cells if "leaf.py" not in c.source]
    nbformat.write(nb, str(nb_path))

    out_dir = tmp_path / "restored"
    reverse(nb_path, out_dir)

    assert (out_dir / "top.py").exists()
    assert not (out_dir / "a" / "b" / "c" / "d" / "e" / "f" / "g" / "leaf.py").exists()


def test_reverse_refuses_non_empty_without_force(tmp_path):
    repo = _make_deep_repo(tmp_path)
    nb_path = tmp_path / "out.ipynb"
    convert(repo, nb_path)

    out_dir = tmp_path / "restored"
    out_dir.mkdir()
    (out_dir / "user_file.txt").write_text("precious")

    with pytest.raises(SystemExit) as e:
        reverse(nb_path, out_dir)
    assert "--force" in str(e.value)
    assert (out_dir / "user_file.txt").read_text() == "precious"


def test_reverse_force_overwrites_but_preserves_extras(tmp_path):
    repo = _make_deep_repo(tmp_path)
    nb_path = tmp_path / "out.ipynb"
    convert(repo, nb_path)

    out_dir = tmp_path / "restored"
    out_dir.mkdir()
    (out_dir / "user_file.txt").write_text("precious")
    (out_dir / "top.py").write_text("stale")

    reverse(nb_path, out_dir, force=True)

    assert (out_dir / "user_file.txt").read_text() == "precious"
    assert (out_dir / "top.py").read_text() == (repo / "top.py").read_text()


def test_reverse_default_output_dir(tmp_path, monkeypatch):
    repo = _make_deep_repo(tmp_path)
    monkeypatch.chdir(tmp_path)
    convert(repo, tmp_path / "mybook.ipynb")

    from repo2nb.cli import main
    main(["reverse", str(tmp_path / "mybook.ipynb")])

    assert (pathlib.Path("mybook") / "top.py").exists()
