import pathlib
import sys

import nbformat


def _safe_destination(output_root: pathlib.Path, rel_path: str) -> pathlib.Path | None:
    """Resolve rel_path inside output_root; None if it escapes (traversal attempt)."""
    if not rel_path or rel_path.startswith("/") or "\\" in rel_path:
        return None
    dest = (output_root / rel_path).resolve()
    try:
        dest.relative_to(output_root.resolve())
    except ValueError:
        return None
    return dest


def _strip_writefile_magic(source: str) -> str:
    lines = source.split("\n")
    if lines and lines[0].startswith("%%writefile"):
        lines = lines[1:]
    return "\n".join(lines)


def reverse(notebook_path: pathlib.Path, output_dir: pathlib.Path, force: bool = False):
    try:
        nb = nbformat.read(str(notebook_path), as_version=4)
    except Exception as e:
        sys.exit(f"[repo2nb] Could not read notebook {notebook_path}: {e}")

    tagged = []
    for cell in nb.cells:
        tag = cell.get("metadata", {}).get("repo2nb")
        if isinstance(tag, dict) and tag.get("path"):
            tagged.append((tag["path"], cell))

    if not tagged:
        sys.exit(
            f"[repo2nb] No repo2nb file cells found in {notebook_path} — "
            "this notebook was not generated by repo2nb (or its metadata was stripped)."
        )

    if output_dir.exists() and any(output_dir.iterdir()) and not force:
        sys.exit(
            f"[repo2nb] Output directory '{output_dir}' is not empty. "
            "Use --force to write into it anyway."
        )

    written, skipped = 0, 0
    for rel_path, cell in tagged:
        dest = _safe_destination(output_dir, rel_path)
        if dest is None:
            print(f"[repo2nb] WARNING: refusing unsafe path '{rel_path}' from cell metadata — skipped.")
            skipped += 1
            continue
        content = _strip_writefile_magic(cell.source)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written += 1

    print(f"[repo2nb] Reconstructed {written} file(s) into '{output_dir}'.")
    if skipped:
        print(f"[repo2nb] WARNING: {skipped} cell(s) skipped due to malformed/unsafe metadata.")
